export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';

export const SEARCH_TRACKS = 'SEARCH_TRACKS';
export const SEARCH_TRACKS_READY = 'SEARCH_TRACKS_READY';
export const SEARCH_TRACKS_FAILURE = 'SEARCH_TRACKS_FAILURE';
export const CLEAR_TRACKS_LIST = 'CLEAR_TRACKS_LIST';

export const GET_CURRENT_PLAYING_TRACK = 'GET_CURRENT_PLAYING_TRACK';
export const GET_CURRENT_PLAYING_TRACK_READY = 'GET_CURRENT_PLAYING_TRACK_READY';
export const GET_CURRENT_PLAYING_TRACK_FAILURE = 'GET_CURRENT_PLAYING_TRACK_FAILURE';

export const ADD_TRACK_TO_PLAYER = 'ADD_TRACK_TO_PLAYER'; 
export const REMOVE_TRACK_FROM_PLAYER = 'REMOVE_TRACK_FROM_PLAYER';

export const PLAY_NEXT_TRACK = 'PLAY_NEXT_TRACK'; 
export const PLAY_PREV_TRACK = 'PLAY_PREV_TRACK';

export const GET_DEVICES = 'GET_DEVICES';
export const REMOVE_DEVICES = 'REMOVE_DEVICES';
export const GET_DEVICES_READY = 'GET_DEVICES_READY';
export const GET_DEVICES_FAILURE = 'GET_DEVICES_FAILURE';

export const GET_ME = 'GET_ME';
export const GET_ME_READY = 'GET_ME_READY';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';

export const CHANGE_TRACK_STATE = 'CHANGE_TRACK_STATE';
export const CHANGE_TRACK_STATE_READY = 'CHANGE_TRACK_STATE_READY';
export const CHANGE_TRACK_STATE_FAILURE = 'CHANGE_TRACK_STATE_FAILURE';

export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';
export const GET_USER_PLAYLISTS_READY = 'GET_USER_PLAYLISTS_READY';
export const GET_USER_PLAYLISTS_FAILURE = 'GET_USER_PLAYLISTS_FAILURE';
export const CLEAR_PLAYLISTS = 'CLEAR_PLAYLISTS';
export const EXPAND_PLAYLIST = 'EXPAND_PLAYLIST';

export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';
export const GET_PLAYLIST_TRACKS_READY = 'GET_PLAYLIST_TRACKS_READY';
export const GET_PLAYLIST_TRACKS_FAILURE = 'GET_PLAYLIST_TRACKS_FAILURE';
export const CLEAR_PLAYLIST_TRACKS = 'CLEAR_PLAYLIST_TRACKS';