export const SEARCH_TRACKS = 'SEARCH_TRACKS';
export const SEARCH_TRACKS_READY = 'SEARCH_TRACKS_READY';
export const SEARCH_TRACKS_FAILURE = 'SEARCH_TRACKS_FAILURE';

export const GET_CURRENT_PLAYING_TRACK = 'GET_CURRENT_PLAYING_TRACK';
export const GET_CURRENT_PLAYING_TRACK_READY = 'GET_CURRENT_PLAYING_TRACK_READY';
export const GET_CURRENT_PLAYING_TRACK_FAILURE = 'GET_CURRENT_PLAYING_TRACK_FAILURE';

